### ISSUE TITLE
MySQLと繋がらないエラー

### ISSUE THREAD

**Issue by OrlyIdeate** [OrlyIdeate/Slack-bot#12]
## エラーが出た時の状況
`python app.py`でアプリを起動させ、Slackのdecチャンネルで`@search`や`@save`などDBと接続する処理を含むとエラーが出た。

## エラー内容
フォームから質問を入力し送信したときに出たエラーです。
```
Failed to run listener function (error: 2003 (HY000): Can't connect to MySQL server on '34.135.69.97:3306' (110))
Traceback (most recent call last):
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on '34.135.69.97:3306' (110)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/home/orlyideate/Slack-bot/modules/modal.py", line 51, in modal_submit
    response_text = chatgpt(question)
  File "/home/orlyideate/Slack-bot/modules/chatgpt.py", line 62, in chatgpt
    top_5_similar_texts = get_top_5_similar_texts(message_text)
  File "/home/orlyideate/Slack-bot/modules/similarity.py", line 43, in get_top_5_similar_texts
    db_connection = mysql.connector.connect(**config)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '34.135.69.97:3306' (110)
```
<br>
一番下の`mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '34.135.69.97:3306' (110)`を見るにMySQLに繋がらないエラーだと思います。

**Comment by OrlyIdeate** [comment]
Configはあってるはずです。。

**Comment by OrlyIdeate** [comment]
グローバルIPアドレスが変更されてDB認証されなかっただけでした。

**Comment by OrlyIdeate** [comment]
グローバルIPアドレスが変更されてないのにDBに接続されないエラー
```
ERROR:slack_bolt.App:Failed to run listener function (error: 2003 (HY000): Can't connect to MySQL server on '35.223.243.48:3306' (111))
Traceback (most recent call last):
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on '35.223.243.48:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/home/orlyideate/Slack-bot/modules/modal.py", line 252, in open_modal
    categories = get_unique_categories()  # データベースからカテゴリーを取得
  File "/home/orlyideate/Slack-bot/modules/upload.py", line 61, in get_unique_categories
    categories = execute_query("SELECT DISTINCT category FROM phese4")
  File "/home/orlyideate/Slack-bot/modules/DB.py", line 36, in execute_query
    connection = connect_to_db()
  File "/home/orlyideate/Slack-bot/modules/DB.py", line 24, in connect_to_db
    return mysql.connector.connect(**config)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/home/orlyideate/Slack-bot/.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '35.223.243.48:3306' (111)
```
